### ISSUE TITLE
No way to set the base url?

### ISSUE THREAD

**Issue by dcermak** [MarcoMuellner/openapi-python-generator#14]
**Describe the bug**

I am probably not looking in the right places, but how does one set the baseurl of the API instance one wants to connect to? There is `APIConfig.base_path`, but that is automatically set to something like `/api/v$whatever/` depending on the actual api in question. So how would one set the actual base url?

**Comment by MarcoMuellner** [comment]
You wouldn't need to, as you would generally generate the client from the API you are using. In the openapi definitions it also defines a `servers` category, in which the servers then would be defined. 

How would you see a use case where this wasn't the case?

**Comment by dcermak** [comment]
For instance when generating a general purpose API wrapper for something like gitea, where everyone can host an instance. It would be quite useful if I wouldn't have to hardcode the url to e.g. `gitea.opensuse.org` as that would prevent anyone from using this wrapper for `codeberg.org`. Especially I would have to duplicate the whole module, if I wanted to communicate with two or more instances at the same time (e.g. to transfer repos).

**Comment by MarcoMuellner** [comment]
I see where you are coming from. So what is it precisely you would expect? Setting the base_path during generation (which would defeat the point), or during runtime? If it is during runtime, wouldn't it suffice to just replace the `APIConfig.base_path` during the startup of your application?

**Comment by dcermak** [comment]
Well, ideally I'd refactor the API so that one would either call all the current API functions as methods of an `API` object, e.g. as follows:
```Python
gitea_o_o = Api(baseurl="https://gitea.opensuse.org")
sha = await gitea_o_o.repoFindGitCommit("rpms", "skopeo", "factory")
```
or to pass a `Conf` instance as a parameter to each API function, e.g. as follows:
```Python
gitea_o_o_conf = ApiConf(baseurl="https://gitea.opensuse.org")
sha = await repoFindGitCommit(gitea_o_o_conf, "rpms", "skopeo", "factory")
```

Both are more or less equivalent and just come down to personal taste. But both would allow you to call multiple instances of the same API without hardcoding anything or having to touch the autogenerated code at all (I'd very much prefer to not having to touch the autogenerated code as that would allow me to periodically create it in a CI)

**Comment by MarcoMuellner** [comment]
Yeah, i can see where you are coming from. I'll take that on my list.

**Comment by dcermak** [comment]
Thank you!

**Comment by MarcoMuellner** [comment]
This should now be possible by passing a `APIConfig()` object at the end of the function. It is the same as the normal APIConfig object (which is now an instance instead of it being a static class), and you can override the IP Adress as wanted.
