### ISSUE TITLE
OperationId is not defined for post

### ISSUE THREAD

**Issue by yuexl** [MarcoMuellner/openapi-python-generator#31]
when i use cmd openapi-python-generator, get an exception:
  /python3.8/site-packages/openapi_python_generator/language_converters/python/service_generator.py", line 158, in generate_operation_id
      raise Exception(f"OperationId is not defined for {http_op}")  # pragma: no cover
  Exception: OperationId is not defined for post

here is the openapi json file:
![image](https://user-images.githubusercontent.com/26302906/232174080-36317e2a-eed0-4fad-8105-f07f9c716dc6.png)

**Comment by MarcoMuellner** [comment]
Please provide an openapi.json file that i can use to test this.

**Comment by yuexl** [comment]
`{
  "openapi": "3.0.1",
  "info": {
    "title": "searchword",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/apipath/login": {
      "post": {
        "summary": "login接口",
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "username",
            "in": "query",
            "description": "",
            "required": true,
            "example": "{{username}}",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "passwd",
            "in": "query",
            "description": "",
            "required": true,
            "example": "{{passwd}}",
            "schema": {
              "type": "string"
            }
          }
        ]
      }
    }
  }
}`


> this file is generated by Apifox which is an api toolkit.

**Comment by MarcoMuellner** [comment]
This is not a valid Openapi document. Every operation usable for the generator must have such an operation id, as it is used to generate naming. For more information, see here:

https://swagger.io/docs/specification/paths-and-operations/

especially the section on operationId

I added a custom exception that will identify this issue better.
