### ISSUE TITLE
The code generates illegal module names with dash - in them

### ISSUE THREAD

**Issue by MagnusNilsson11** [MarcoMuellner/openapi-python-generator#33]
**Describe the bug**
The generator uses the illegal character dash - when naming modules in the services folder.

**To Reproduce**
1. Generate a client from an openapi specification where tags and or paths contains the dash - character
2. Look at the module names in the services folder

**Expected behavior**
That the modules would be named using only legal characters following the Python specification.

**Screenshots**
![image](https://user-images.githubusercontent.com/126265253/233345649-f494d1c3-2d09-475c-b0b7-260f01aeb1bf.png)

**Comment by MarcoMuellner** [comment]
This doesn't seem to difficult, would you want to take this over yourself? I'll help you of course :)

**Comment by MagnusNilsson11** [comment]
Thanks for the offer. Unfortunately I'm just in the process of testing code generators so I can't really dedicate time to help with bugfixes (if we pick this generator we can help of course). Just wanted to let the project know this issue exists. Best of luck with everything.
