### ISSUE TITLE
httpx client stub is broken in version 0.4.6

### ISSUE THREAD

**Issue by oligo** [MarcoMuellner/openapi-python-generator#41]
**Describe the bug**
when generating httpx client stub, json field of the httpx#request method is  passed the serialized object, and thus causing API server panics.

**To Reproduce**
1. openapi-python-generator --library 'httpx' http://api-server/v3/api-docs ./openapi_client/
2. run codes generated above and  api-server will not accept the posted body while it assumes 'application/json'

**Comment by oligo** [comment]
I think all APIs accepting JSON are affetected. I checked the Httpx docs and it says the json param must be "A JSON serializable object to include in the body of the request". I modified the generated code to remove "json.dumps()" and it worked. 

Below is the modified example code:

`   
with httpx.Client(base_url=base_path, verify=api_config.verify) as client:
        response = client.request(
            "post", httpx.URL(path), headers=headers, params=query_params, json=data.dict()
        )
`

**Comment by MarcoMuellner** [comment]
can you provide an openapi.json file to test?

**Comment by oligo** [comment]
Please check the attached openapi docs. Sorry that I cannot provide a server to test that API but I think you can analysis the code first.
[example-openapi-doc.zip](https://github.com/MarcoMuellner/openapi-python-generator/files/11895274/example-openapi-doc.zip)

**Comment by tsiq-aaronk** [comment]
Came here to report this exact bug. The `json=` kwarg of `httpx`'s `request()` expects non-serialized data. I stepped through it and watched it re-JSONify my inputs. The `data=` kwarg is what you want. Or just don't call `json.dumps()` yourself.
